---
- name: Install ufw
  package:
    name: ufw
    state: present
  tags: [firewall]

- name: Allow ports
  become: true
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    # ssh
    - port: 22
      proto: tcp
    # syncthing
    - port: 22000
      proto: tcp
    - port: 21027,
      proto: udp
  tags: [firewall]

- name: Enable ufw now
  become: true
  service:
    name: ufw
    state: restarted
    enabled: true
  tags: [firewall]
