---
- hosts: homeserver
  vars:
    nfs_exports:
      - "/srv/nfs/main 192.168.1.0/24(rw,no_root_squash,async)"
      - "/srv/nfs/aux 192.168.1.0/24(rw,no_root_squash,async)"
      - "/srv/nfs/bak 192.168.1.0/24(rw,no_root_squash,async)"
    zfs_devices:
      - Alsergrund
      - Hietzing
      - main
    zfs_scrub_interval: weekly
    samba_users:
      - name: barnabas
        password: "{{ samba_password }}"
    samba_shares:
      - name: trash
        write_list: barnabas
        valid_users: barnabas
        group: barnabas
        path: /srv/nfs/main/smb

    service_dir: "{{ nfs_main_mount }}/services"

    docker_install_compose: true

  roles:
    - role: geerlingguy.docker
      become: true
    - homeserver
    - role: geerlingguy.nfs
      become: true
    - role: zfs
      become: true
    - role: bertvv.samba
      become: true
