---
# tasks file for podman-services
- name: Install podman depends
  become: true
  apt:
    name:
      - software-properties-common
      - uidmap
    state: present

- name: Add podman repo
  become: true
  apt_repository:
    repo: 'ppa:projectatomic/ppa'

- name: Install podman
  become: true
  apt:
    name:
      - podman
    state: present

- name: Copy podman registry config
  become: true
  copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
  tags: [podman-service]

- name: Template podman services
  become: true
  template:
    src: podman-service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ podman_services }}"
  tags: [podman-service]

- name: Enable podman services
  become: true
  systemd:
    name: "{{ item.name }}"
    daemon_reload: true
    enabled: true
    state: started
  loop: "{{ podman_services }}"
  tags: [podman-service]
