---
- name: Install iwd
  become: true
  pacman:
    name:
      iwd
  tags: [installation]

  #- name: Copy over network connection files
  #  become: true
  #  copy:


- name: Enable iwd
  become: true
  systemd:
    name: iwd
    enabled: true
    state: started
