---
- name: Install ufw
  become: true
  apt:
    name: ufw
    state: present
  tags: [firewall]

- name: Add things to ufw
  become: true
  ufw:
    proto: "{{ item.proto }}"
    rule: allow
    port: "{{ item.port }}"
  loop:
      - port: 22
        proto: tcp

      # pi-hole
      - port: 53
        proto: tcp
      - port: 53
        proto: udp
      - port: 67
        proto: udp
      - port: 8000
        proto: tcp

      # transmission
      - port: 9091
        proto: tcp
      - port: 51413
        proto: tcp
      - port: 51413
        proto: udp

      # nfs
      - port: 2049
        proto: tcp
      - port: 2049
        proto: udp

      # cockpit
      - port: 9090
        proto: tcp

      # unifi
      - port: 8080
        proto: tcp
      - port: 8443
        proto: tcp
      - port: 6789
        proto: tcp
      - port: 3478
        proto: udp
      - port: 10001
        proto: udp
  tags: [firewall]

- name: Enable ufw
  become: true
  ufw:
    state: enabled
    policy: reject
  tags: [firewall]

- name: Enable ufw service
  become: true
  systemd:
    name: ufw
    enabled: true
    state: started
  tags: [firewall]
